---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/davidk355/concourse-tutorial.git
- name: resource-gist
  type: git
  source:
    branch: master
    uri: git@gist.github.com:97a8009d63187aec5475e2f135e5d6f9.git
    branch: master
    private_key: {{git-private-key}}

jobs:
- name: job-bump-date
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-gist
  - task: bump-timestamp-file
    file: resource-tutorial/12_publishing_outputs/bump-timestamp-file.yml
  - put: resource-gist
    params: {repository: updated-gist}
